checks:
  php:
    code_rating: true
    duplication: true
filter:
  paths:
    - src/*
    - tests/*
build:
  environment:
    php:
      version: 8.2
  dependencies:
    before:
      - composer install --no-interaction --prefer-dist
  tests:
    override:
      - command: composer analyse
      - command: composer test
        coverage:
          file: coverage.clover
          format: php-clover
